services:
  django:
    container_name: plantagora_service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./service:/app 
    depends_on:
      - db
    env_file: '.env'
    command: python /app/src/manage.py runserver 0.0.0.0:8001
    restart: always


  db:
    env_file: '.env'
    container_name: plantagora_db
    image: postgres:17
    environment:
      POSTGRES_DB: plantagora_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  docs:
    build:
      context: .
      dockerfile: Mkdocsfile
    container_name: plantagora_docs
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    command: mkdocs serve --dev-addr=0.0.0.0:8002 --dirtyreload --watch /app/docs
    restart: always

  frontend:
    container_name: plantagora_web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

volumes:
  postgres_data: