# Generated by Django 5.1.7 on 2025-03-24 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Code')),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Garden',
                'verbose_name_plural': 'Gardens',
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('document', models.CharField(max_length=20, verbose_name='Document')),
                ('documentType', models.CharField(choices=[(1, 'CPF'), (2, 'CNPJ'), (3, 'RG'), (4, 'IE'), (5, 'IM'), (6, 'PASSPORT'), (7, 'CNH'), (8, 'CTPS'), (9, 'OTHER')], default=1, max_length=1, verbose_name='Document Type')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grower', related_query_name='grower', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Grower',
                'verbose_name_plural': 'Growers',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, max_length=1, verbose_name='Status')),
                ('releasedAt', models.DateTimeField(auto_now_add=True, verbose_name='Released At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('endedAt', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', related_query_name='signature', to='plantagora.garden', verbose_name='Garden')),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', related_query_name='signature', to='plantagora.grower', verbose_name='Grower')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
        migrations.CreateModel(
            name='GardenBed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Code')),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, max_length=1, verbose_name='Status')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardenBeds', related_query_name='gardenBed', to='plantagora.garden', verbose_name='Garden')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardenBeds', related_query_name='gardenBed', to='plantagora.signature', verbose_name='Signature')),
            ],
            options={
                'verbose_name': 'Garden Bed',
                'verbose_name_plural': 'Garden Beds',
            },
        ),
    ]
