# Generated by Django 5.1.7 on 2025-03-24 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantagora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complement')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, max_length=1, verbose_name='Status')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='plantagora.garden', verbose_name='Garden')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
