# Generated by Django 5.1.7 on 2025-04-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="state",
        ),
    ]
