# Generated by Django 5.2 on 2025-04-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantagora', '0002_remove_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='duration',
            field=models.IntegerField(choices=[(1, 'Um mês'), (3, 'Três meses'), (6, 'Seis meses'), (12, 'Doze meses')], default=12, verbose_name='Duration'),
        ),
    ]
