# Generated by Django 5.1.7 on 2025-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantagora', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grower',
            name='documentType',
            field=models.IntegerField(choices=[(1, 'CPF'), (2, 'CNPJ'), (3, 'RG'), (4, 'IE'), (5, 'IM'), (6, 'PASSPORT'), (7, 'CNH'), (8, 'CTPS'), (9, 'OTHER')], default=1, verbose_name='Document Type'),
        ),
    ]
