# Generated by Django 5.2 on 2025-04-14 05:13

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0003_signature_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signature",
            name="endedAt",
        ),
        migrations.AlterField(
            model_name="grower",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grower",
                related_query_name="grower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="releasedAt",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Released At"
            ),
        ),
    ]
