# Generated by Django 5.2 on 2025-04-14 05:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0005_gardenbed_address"),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                ("number", models.CharField(max_length=10, verbose_name="Number")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Complement"
                    ),
                ),
                ("zip_code", models.CharField(max_length=8, verbose_name="Zip Code")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        related_query_name="address",
                        to="utils.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.RemoveField(
            model_name="gardenbed",
            name="address",
        ),
        migrations.AddField(
            model_name="grower",
            name="caf",
            field=models.CharField(
                blank=True,
                help_text="Cadastro Nacional da Agricultura Familiar ou ao Número de Autorização Centralizada",
                max_length=9,
                null=True,
                verbose_name="CAF",
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="levelOfEducation",
            field=models.IntegerField(
                choices=[
                    (1, "Ensino Fundamental"),
                    (2, "Ensino Médio"),
                    (3, "Graduação"),
                    (4, "Pós-Graduação"),
                ],
                default=1,
                verbose_name="Level of Education",
            ),
        ),
        migrations.AlterField(
            model_name="grower",
            name="documentType",
            field=models.IntegerField(
                choices=[(1, "CPF"), (2, "CNPJ"), (0, "Outro")],
                default=1,
                verbose_name="Document Type",
            ),
        ),
        migrations.CreateModel(
            name="GardenAddress",
            fields=[
                (
                    "baseaddress_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plantagora.baseaddress",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        related_query_name="address",
                        to="plantagora.garden",
                        verbose_name="Garden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garden Address",
                "verbose_name_plural": "Garden Addresses",
            },
            bases=("plantagora.baseaddress",),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AddField(
            model_name="gardenbed",
            name="garden_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gardenBeds",
                related_query_name="gardenBed",
                to="plantagora.gardenaddress",
                verbose_name="Address",
            ),
        ),
    ]
