# Generated by Django 5.2 on 2025-04-14 06:16

import datetime
import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0008_alter_baseaddress_options_grower_address"),
        ("utils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="grower",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plantagora.baseaddress",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="grower",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profile",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalBaseAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                ("number", models.CharField(max_length=10, verbose_name="Number")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Complement"
                    ),
                ),
                ("zip_code", models.CharField(max_length=8, verbose_name="Zip Code")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="address",
                        to="utils.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Base Address",
                "verbose_name_plural": "historical Base Addresses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGarden",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Code",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Garden",
                "verbose_name_plural": "historical Gardens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGardenAddress",
            fields=[
                (
                    "baseaddress_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="plantagora.baseaddress",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                ("number", models.CharField(max_length=10, verbose_name="Number")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Complement"
                    ),
                ),
                ("zip_code", models.CharField(max_length=8, verbose_name="Zip Code")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="address",
                        to="utils.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="address",
                        to="plantagora.garden",
                        verbose_name="Garden",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Garden Address",
                "verbose_name_plural": "historical Garden Addresses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGardenBed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Code",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="gardenBed",
                        to="plantagora.garden",
                        verbose_name="Garden",
                    ),
                ),
                (
                    "garden_address",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="gardenBed",
                        to="plantagora.gardenaddress",
                        verbose_name="Garden Address",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="gardenBed",
                        to="plantagora.signature",
                        verbose_name="Signature",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Garden Bed",
                "verbose_name_plural": "historical Garden Beds",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGrower",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "caf",
                    models.CharField(
                        blank=True,
                        help_text="Cadastro Nacional da Agricultura Familiar ou ao Número de Autorização Centralizada",
                        max_length=9,
                        null=True,
                        verbose_name="CAF",
                    ),
                ),
                (
                    "levelOfEducation",
                    models.IntegerField(
                        choices=[
                            (1, "Ensino Fundamental"),
                            (2, "Ensino Médio"),
                            (3, "Graduação"),
                            (4, "Pós-Graduação"),
                        ],
                        default=1,
                        verbose_name="Level of Education",
                    ),
                ),
                ("document", models.CharField(max_length=20, verbose_name="Document")),
                (
                    "documentType",
                    models.IntegerField(
                        choices=[(1, "CPF"), (2, "CNPJ"), (0, "Outro")],
                        default=1,
                        verbose_name="Document Type",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="plantagora.baseaddress",
                        verbose_name="Address",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Grower",
                "verbose_name_plural": "historical Growers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (1, "Um mês"),
                            (3, "Três meses"),
                            (6, "Seis meses"),
                            (12, "Doze meses"),
                        ],
                        default=12,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "releasedAt",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Released At"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="signature",
                        to="plantagora.garden",
                        verbose_name="Garden",
                    ),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="signature",
                        to="plantagora.grower",
                        verbose_name="Grower",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Signature",
                "verbose_name_plural": "historical Signatures",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
