# Generated by Django 5.2 on 2025-04-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantagora', '0009_alter_grower_address_alter_grower_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalgrower',
            name='name',
        ),
    ]
