# Generated by Django 5.2 on 2025-05-16 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0010_remove_grower_name_remove_historicalgrower_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grower",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Masculino"), (2, "Feminino"), (3, "Outro")],
                default=3,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="registerApproved",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o registro do produtor foi aprovado.",
                verbose_name="Register Approved",
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="registerApprovedAt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Register Approved At"
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="registerApprovedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Register Approved By",
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="registeredAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Registered At"
            ),
        ),
        migrations.AddField(
            model_name="grower",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Masculino"), (2, "Feminino"), (3, "Outro")],
                default=3,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="registerApproved",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o registro do produtor foi aprovado.",
                verbose_name="Register Approved",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="registerApprovedAt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Register Approved At"
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="registerApprovedBy",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Register Approved By",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="registeredAt",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Registered At"
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="updatedAt",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="grower",
            name="documentType",
            field=models.IntegerField(
                choices=[(1, "CPF"), (2, "CNPJ")],
                default=1,
                verbose_name="Document Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrower",
            name="documentType",
            field=models.IntegerField(
                choices=[(1, "CPF"), (2, "CNPJ")],
                default=1,
                verbose_name="Document Type",
            ),
        ),
    ]
