# Generated by Django 5.2 on 2025-05-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0011_grower_gender_grower_registerapproved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grower",
            name="cell",
            field=models.CharField(
                blank=True,
                help_text="Número de celular do produtor.",
                max_length=11,
                null=True,
                verbose_name="Cell",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="cell",
            field=models.CharField(
                blank=True,
                help_text="Número de celular do produtor.",
                max_length=11,
                null=True,
                verbose_name="Cell",
            ),
        ),
    ]
