# Generated by Django 5.2 on 2025-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0012_grower_cell_historicalgrower_cell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grower",
            name="documentType",
        ),
        migrations.RemoveField(
            model_name="historicalgrower",
            name="documentType",
        ),
        migrations.AddField(
            model_name="grower",
            name="birthDate",
            field=models.DateField(
                blank=True,
                help_text="Data de nascimento do produtor.",
                null=True,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AddField(
            model_name="historicalgrower",
            name="birthDate",
            field=models.DateField(
                blank=True,
                help_text="Data de nascimento do produtor.",
                null=True,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AlterField(
            model_name="grower",
            name="document",
            field=models.CharField(max_length=11, unique=True, verbose_name="Document"),
        ),
        migrations.AlterField(
            model_name="historicalgrower",
            name="document",
            field=models.CharField(
                db_index=True, max_length=11, verbose_name="Document"
            ),
        ),
    ]
