# Generated by Django 5.2 on 2025-06-23 00:37

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantagora", "0013_remove_grower_documenttype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocioeconomicQuestionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the socioeconomic questionnaire.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the socioeconomic questionnaire.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON object containing the questions and their alternatives.",
                        verbose_name="Questions",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "releasedAt",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Released At"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Socioeconomic Questionnaire",
                "verbose_name_plural": "Socioeconomic Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="HistoricalSocioeconomicQuestionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the socioeconomic questionnaire.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the socioeconomic questionnaire.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON object containing the questions and their alternatives.",
                        verbose_name="Questions",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "releasedAt",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Released At"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Socioeconomic Questionnaire",
                "verbose_name_plural": "historical Socioeconomic Questionnaires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSocioeconomicProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON object containing the answers to the questionnaire.",
                        verbose_name="Answers",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="plantagora.grower",
                        verbose_name="Grower",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionaire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="plantagora.socioeconomicquestionnaire",
                        verbose_name="Socioeconomic Questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Socioeconomic Profile",
                "verbose_name_plural": "historical Socioeconomic Profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SocioeconomicProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON object containing the answers to the questionnaire.",
                        verbose_name="Answers",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ativo"), (2, "Inativo")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socioeconomic_profiles",
                        to="plantagora.grower",
                        verbose_name="Grower",
                    ),
                ),
                (
                    "questionaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="plantagora.socioeconomicquestionnaire",
                        verbose_name="Socioeconomic Questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socioeconomic Profile",
                "verbose_name_plural": "Socioeconomic Profiles",
                "ordering": ["-submitted_at"],
                "unique_together": {("questionaire", "grower")},
            },
        ),
    ]
