# Generated by Django 5.2 on 2025-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_historicalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="profilePicture",
            field=models.TextField(
                blank=True,
                help_text="A foto de perfil do usuário.",
                max_length=100,
                null=True,
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profilePicture",
            field=models.ImageField(
                blank=True,
                help_text="A foto de perfil do usuário.",
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
