name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSKEY }}
          port: 22
          script: |
            cd ${{ secrets.VM_PWD }}

            git checkout .
            git pull origin main -f

            rm -f .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

            docker compose up --build -d

            sudo systemctl restart nginx