name: Lint and Test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file for Docker Compose
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=plantagora_db" >> .env
          echo "DB_HOST=plantagora_db" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Show Docker Compose version
        run: docker compose version

      - name: Build and start lint container
        run: docker compose up --build -d lint

      - name: Wait for lint container to finish
        run: |
          docker logs -f plantagora_lint
          docker wait plantagora_lint
          exit_code=$(docker inspect plantagora_lint --format='{{.State.ExitCode}}')
          if [ "$exit_code" -ne 0 ]; then
            echo "Lint container failed"
            exit $exit_code
          fi

      - name: Build and start db and test containers
        run: docker compose up --build -d db test

      - name: Wait for test container to finish
        run: |
          docker logs -f plantagora_test
          docker wait plantagora_test
          exit_code=$(docker inspect plantagora_test --format='{{.State.ExitCode}}')
          if [ "$exit_code" -ne 0 ]; then
            echo "Test container failed"
            exit $exit_code
          fi

      - name: Tear down containers
        run: docker compose down
