name: Lint and Test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (para builds multi-arch se precisar)
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          version: 'v2.20.2'  # ou outra versão que preferir

      - name: Build and start lint container
        run: docker-compose up --build -d lint

      - name: Run lint and wait for completion
        run: |
          docker logs -f plantagora_lint
          docker wait plantagora_lint
          docker inspect plantagora_lint --format='{{.State.ExitCode}}' | grep '^0$'

      - name: Build and start test container (aguardando banco)
        run: docker-compose up --build -d db test

      - name: Wait for tests to finish
        run: |
          docker logs -f plantagora_test
          docker wait plantagora_test
          docker inspect plantagora_test --format='{{.State.ExitCode}}' | grep '^0$'

      - name: Tear down containers
        run: docker-compose down